# Generated by Django 5.2.7 on 2026-03-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('staples', 'Staples'), ('proteins', 'Proteins'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('snacks', 'Snacks'), ('drinks', 'Drinks')], max_length=50)),
                ('serving_unit', models.CharField(default='g', max_length=20)),
                ('default_serving_size', models.FloatField(default=100)),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('fats_per_100g', models.FloatField()),
                ('fiber_per_100g', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('portion_size', models.FloatField(help_text='Portion size in grams/ml')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-logged_at'],
            },
        ),
    ]
