# Generated by Django 5.2.7 on 2026-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='source',
            field=models.CharField(choices=[('local', 'kenyan_food_fixture'), ('usda', 'USDA')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='usda_fdc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('name', 'source')},
        ),
    ]
