# Generated by Django 5.2.7 on 2026-03-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_fooditem_source_fooditem_usda_fdc_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='portion_size',
        ),
        migrations.AddField(
            model_name='meallog',
            name='carbs_portion',
            field=models.FloatField(default=0, help_text='Carbs in grams '),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fats_portion',
            field=models.FloatField(default=0, help_text='fats iin grams'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='protein_portion',
            field=models.FloatField(default=0, help_text='Protein in grams'),
        ),
    ]
