# Generated by Django 5.2.7 on 2026-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_remove_meallog_portion_size_meallog_carbs_portion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='portion_size',
            field=models.FloatField(default=100, help_text='Portion in grams'),
        ),
    ]
