# Generated by Django 5.2.7 on 2026-02-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos/'),
        ),
    ]
