# Generated by Django 5.2.7 on 2026-02-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_duration_exercise_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='total_programs',
        ),
    ]
