# Generated by Django 5.2.7 on 2026-02-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_category_total_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.CharField(default='10', help_text="e.g. '10', '10-12', 'to failure'", max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_time',
            field=models.PositiveIntegerField(default=60, help_text='Rest in seconds'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.CharField(blank=True, default='Bodyweight', help_text="e.g. '5-8kg', 'Bodyweight', '18kg+'", max_length=50),
        ),
    ]
