# Generated by Django 5.2.7 on 2026-02-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_level_exercise_reps_exercise_rest_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['category', 'muscle_group', 'level', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='training_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('hiit', 'HIIT'), ('cardio', 'Cardio'), ('mobility', 'Mobility')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='distance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('hiit', 'HIIT'), ('cardio', 'Cardio'), ('mobility', 'Mobility')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='hiit_rest_time',
            field=models.PositiveIntegerField(blank=True, help_text='Rest duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='intensity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rounds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='work_time',
            field=models.PositiveIntegerField(blank=True, help_text='Work duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest_time',
            field=models.PositiveIntegerField(blank=True, help_text='Rest in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('glutes', 'Glutes'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=50, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='muscle_groups', to='exercises.category')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exercises.musclegroup'),
        ),
        migrations.DeleteModel(
            name='UserExercises',
        ),
    ]
