# Generated by Django 5.2.7 on 2026-03-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise_equipment_exercise_instructions_exerciselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='demo_video',
            field=models.URLField(blank=True, help_text='https://pub-a3e3770ca86b453197bf4160321b1b0a.r2.dev', null=True),
        ),
    ]
