# Generated by Django 5.2.7 on 2026-04-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_exercise_demo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='cardio_tips',
            field=models.TextField(blank=True, help_text='Cardio exercises only. One tip per line, e.g:\n* Walk at a steady pace\n* Keep posture upright\n* Swing arms naturally\n* Maintain rhythmic breathing'),
        ),
    ]
