# Generated by Django 5.2.7 on 2026-04-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_exercise_cardio_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='cardio_tips',
        ),
    ]
