# Generated by Django 5.2.7 on 2025-11-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('goal_type', models.CharField(max_length=50)),
                ('activity_level', models.CharField(max_length=50)),
                ('fitness_level', models.CharField(max_length=50)),
                ('prefered_focus', models.TextField()),
                ('equipment', models.TextField()),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
