# Generated by Django 5.2.7 on 2026-02-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='backup_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
