# Generated by Django 5.2.7 on 2026-03-06 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise_equipment_exercise_instructions_exerciselog'),
        ('users', '0009_remove_userprofile_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('cm', 'cm'), ('inches', 'inches')], default='cm', max_length=10)),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('arms', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('thighs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress_photos/')),
                ('label', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('progress', 'Progress')], default='progress', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StrengthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_lifted', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=3)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('sets_done', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('auto_logged', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_logs', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('build_muscle', 'Build Muscle'), ('stay_active', 'Stay Active'), ('improve_endurance', 'Improve Endurance'), ('flexibility', 'Flexibility & Mobility')], default='stay_active', max_length=30)),
                ('preferred_days', models.JSONField(blank=True, default=list)),
                ('units', models.CharField(choices=[('metric', 'Metric (kg, cm)'), ('imperial', 'Imperial (lbs, inches)')], default='metric', max_length=10)),
                ('dark_mode', models.BooleanField(default=True)),
                ('notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=3)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
