# Generated by Django 5.2.7 on 2026-03-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_mealplan_mealplanday_mealplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wants_meal_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='quantity',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='quantity_unit',
            field=models.CharField(default='g', max_length=50),
        ),
    ]
