# Generated by Django 5.2.7 on 2026-03-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userprofile_age_remove_userprofile_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='equipment',
        ),
    ]
